Document: hyphen-indic
Title: Debian hyphen-indic Manual
Author: <insert document author here>
Abstract: This manual describes what hyphen-indic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hyphen-indic/hyphen-indic.sgml.gz

Format: postscript
Files: /usr/share/doc/hyphen-indic/hyphen-indic.ps.gz

Format: text
Files: /usr/share/doc/hyphen-indic/hyphen-indic.text.gz

Format: HTML
Index: /usr/share/doc/hyphen-indic/html/index.html
Files: /usr/share/doc/hyphen-indic/html/*.html
